### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by nagaraj786** [roma-sck/SocialApp#1]
Hi,

I have configured Firebase account and implemented the  json file in this project app and i unable to login or create user. can you please explain how to implement this project in firebase and what changes we have to make in our app. kindly send the details.

**Comment by roma-sck** [comment]
Hi,
If you want to use your own account, in order to allow login to your app, you should allow authentication via email and password in tab Authentication/Sign-in method in your project settings (https://console.firebase.google.com/project/YOUR_PROJECT/authentication/providers)
Also, you should check Database rules in your project settings (https://console.firebase.google.com/project/YOUR_PROJECT/database/YOUR_PROJECT/rules). My project uses below configs
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
That's all

**Comment by nagaraj786** [comment]
Done! 

Thank You very much
